# [InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
offsets:
  main: ["018C", "0000"]
  character: ["0004", "3FFFC"]

definitions:
  base_character: CAPTAIN
  series_logo_css: ZELDA
  series_logo_model: ZELDA
  select_pose: 4

name: "Ganondorf Plus" 
num_costumes: 8

results:
  name: "Ganondorf Plus"
  name_scale: 0.5
  name_x: 20
  wins_x: 185
  
# Files 6, 7, 8, 9
# [Filename (without .bin), InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
files: [
  "0",
  "File.GND_ENTRY_KICK",
  "File.GND_PUNCH_GRAPHIC",
  "0"
]