# [InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
name: "Uncanny Mansion"

series: WARIO

sss_zoom: 0.47

offsets:
  header: ["0098", "0014"]
  stage: ["2FD4", "3FFFC"]
  background: ["269D0", "3FFFC"]

mushroom_kingdom_camera: true

magnifying_glass_color: [140, 74, 230] # Either HTML color or [R, G, B]

music:
  main: WARIOWORLD_HORROR_MANOR
  occasional: -1
  rare: -1
  rare2: -1

spawn_locations:
  default:
    p1: [-0166,3275]
    p2: [2325,4315]
    p3: [-2399,2690]
    p4: [2403,1791]
  neutral:
    p1: [-0166,3275]
    p2: [2325,4315]
    p3: [-2399,2690]
    p4: [2403,1791]
