name: Build Project

on:
  push:
  pull_request:

jobs:
  cleanup-old-artifacts:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Remove old build artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 days'
          skip-recent: 1

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Set up Python and Pipenv
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies from Pipfile
        run: |
            pipenv install --dev
            pipenv install gdown

      - name: Install system dependencies (tkinter)
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Setup X virtual framebuffer (Xvfb) - Needed for wine
        run: |
            sudo apt install -y xvfb
            export DISPLAY=:99
            Xvfb :99 -screen 0 1024x768x16 &

      - name: Install Wine
        run: |
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install -y wine winetricks
            DISPLAY=:99 winetricks --force -q vcrun2015 || true
            DISPLAY=:99 winetricks --force -q vcrun2017 || true
            DISPLAY=:99 winetricks --force -q vcrun2019 || true

      - name: Download assets
        run: |
            mkdir -p smashremix/roms
            pipenv run gdown "$ASSETS_LINK" -O smashremix/roms/ssb.rom
        env:
          ASSETS_LINK: ${{ secrets.ASSETS_LINK }}

      - name: Build Project
        run: |
            pipenv run python character_appender.py
            sed -i '/pause/d' patch_extra.bat
            DISPLAY=:99 wine patch_extra.bat

      - name: Display char_data.csv as table in summary
        run: |
            cd smashremix
            pipenv install pandas
            pipenv run python scripts/attributes_dump.py --rom ../ssb64asm_extra.z64 --file_asm ../src/File.asm
            echo "### Character Data Table" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            head -n 1 char_data.csv | awk -F',' '{printf "|"; for(i=1;i<=NF;i++) printf " %s |", $i; print ""}' >> $GITHUB_STEP_SUMMARY
            head -n 1 char_data.csv | awk -F',' '{printf "|"; for(i=1;i<=NF;i++) printf " --- |"; print ""}' >> $GITHUB_STEP_SUMMARY
            tail -n +2 char_data.csv | awk -F',' '{printf "|"; for(i=1;i<=NF;i++) printf " %s |", $i; print ""}' >> $GITHUB_STEP_SUMMARY

      - name: Upload char_data.csv as artifact
        uses: actions/upload-artifact@v4
        with:
            name: char_data_csv
            path: smashremix/char_data.csv
    
      - name: Generate xdelta patch
        run: DISPLAY=:99 wine gen_patch.bat

      - name: Upload xdelta patch as artifact
        uses: actions/upload-artifact@v4
        with:
          name: smashremix_extra_patch
          path: smashremix_extra.xdelta

      - name: Generate RDB file
        run: |
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY
            python scripts/gen_rdb.py | tee -a $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Generate INI file
        run: |
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY
            python scripts/gen_ini.py | tee -a $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
